# Generated by Django 5.1.6 on 2025-04-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_imagesentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='URLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('post_text', models.TextField()),
                ('text_sentiment', models.CharField(max_length=10)),
                ('image_sentiment', models.CharField(blank=True, max_length=10, null=True)),
                ('image_file', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ImageSentiment',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
