# Generated by Django 5.1.6 on 2025-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_textprediction_urlprediction_delete_imagesentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlprediction',
            name='image_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
